apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-{{ .Values.appName }}
  namespace: istio-system
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}

          args:
            {{ if .Values.logging.json }}
            - "--json"
            {{ end }}
            - "--port={{ .Values.service.port }}"
            - "--level={{ .Values.logging.level }}"
            - "--hash-key={{ .Values.keys.hashKeySize }}"
            - "--block-key={{ .Values.keys.blockKeySize }}"
            {{ if .Values.secureCookies }}
            - "--secure-cookies"
            {{ end }}

          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: transient-storage
              mountPath: /volume
      volumes:
        - name: transient-storage
          emptyDir: {}
