apiVersion: apiextensions.k8s.io/v1beta1
kind:       CustomResourceDefinition
metadata:
    name: policies.security.cloud.ibm.com
spec:
    group: security.cloud.ibm.com
    versions:
        - name:    v1
          served:  true
          storage: true
    scope: Namespaced
    names:
        plural:   policies
        singular: policy
        kind:     Policy
    validation:
        openAPIV3Schema:
            properties:
                spec:
                    required:
                        - targets
                    properties:
                        targets:
                            type: array
                            items:
                                type: object
                                required:
                                    - serviceName
                                    - paths
                                properties:
                                    serviceName:
                                        type:      string
                                        minLength: 1
                                    serviceHost:
                                        type: array
                                        items:
                                            type: string
                                    paths:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                exact:
                                                    type:      string
                                                    minLength: 1
                                                prefix:
                                                    type:      string
                                                    minLength: 1
                                                method:
                                                    type: string
                                                    enum:
                                                        - ALL
                                                        - GET
                                                        - DELETE
                                                        - POST
                                                        - PUT
                                                policies:
                                                    type:      array
                                                    items:
                                                        type: object
                                                        required:
                                                            - policyType
                                                            - config
                                                        properties:
                                                            policyType:
                                                                type:      string
                                                                enum:
                                                                    - jwt
                                                                    - oidc
                                                            config:
                                                                type:      string
                                                                minLength: 1
                                                            redirectUri:
                                                                type:    string
                                                                pattern: '^(?:http(s)?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$'
                                                            rules:
                                                                type:       array
                                                                items:
                                                                    type:   object
                                                                    required:
                                                                        - claim
                                                                        - values
                                                                    properties:
                                                                        claim:
                                                                            type:      string
                                                                            minLength: 1
                                                                        source:
                                                                            type:      string
                                                                            enum:
                                                                                - access_token
                                                                                - id_token
                                                                        match:
                                                                            type: string
                                                                            enum:
                                                                                - ALL
                                                                                - ANY
                                                                                - NOT
                                                                        values:
                                                                            type:      array
                                                                            items:
                                                                                type: string